import React, { createContext, useContext, useState, useCallback } from "react";

const translations = {
  fr: {
    nav: { shop: "Boutique", smartHome: "Maison connectée", workspace: "Télétravail", security: "Sécurité", story: "Manifeste", blog: "Journal", contact: "Contact", account: "Compte", admin: "Admin", login: "Connexion", logout: "Déconnexion", cart: "Panier" },
    hero: { overline: "Domotique premium · Livraison Europe", l1: "La maison", l2: "qui pense", l3: "à votre place.", sub: "Invovix conçoit un écosystème connecté pour la maison intelligente et le télétravail. Objets pensés, livrés dans toute la zone euro.", cta: "Découvrir la boutique", cta2: "Notre manifeste" },
    marquee: ["Maison connectée", "Télétravail", "Sécurité intelligente", "Livraison Europe", "Support FR / EN"],
    featured: { overline: "Sélection", title: "Les essentiels connectés", sub: "Une curation d'objets techniques pour transformer votre quotidien.", all: "Voir toute la boutique" },
    categories: { overline: "Univers", title: "Explorez par usage", smartHome: "Maison connectée", smartHomeD: "Éclairage, thermostats, hubs.", workspace: "Télétravail", workspaceD: "Bureaux augmentés, sans fil.", security: "Sécurité", securityD: "Caméras & capteurs intelligents." },
    manifesto: { overline: "Le manifeste Invovix", c1t: "La technologie disparaît", c1d: "Le meilleur objet connecté est celui qu'on oublie. Il agit, anticipe et s'efface. Nous concevons pour la simplicité radicale.", c2t: "Fabriqué pour durer", c2d: "Chaque produit est sélectionné pour sa fiabilité et son intégration native à votre écosystème existant.", c3t: "Livré en Europe", c3d: "Une logistique pensée pour la zone euro. Prix en euros, support bilingue, livraison suivie." },
    trust: { free: "Livraison offerte dès 50€", freeD: "Partout en zone euro", secure: "Paiement sécurisé", secureD: "Stripe & PayPal, cryptage SSL", support: "Support bilingue", supportD: "Assistance FR / EN 7j/7", returns: "Retours 30 jours", returnsD: "Satisfait ou remboursé" },
    cta: { title: "Prêt à connecter votre intérieur ?", sub: "Rejoignez les foyers qui ont choisi l'intelligence discrète.", btn: "Commencer" },
    shop: { title: "La boutique", sub: "Tous nos objets connectés, sélectionnés pour l'Europe.", filterAll: "Tout", empty: "Aucun produit trouvé.", search: "Rechercher…" },
    product: { add: "Ajouter au panier", added: "Ajouté au panier", buy: "Acheter maintenant", desc: "Description", back: "Retour", inStock: "En stock", outOfStock: "Épuisé", lowStock: "Plus que {n} en stock", variant: "Modèle", qty: "Quantité", save: "Économisez" },
    cart: { title: "Votre panier", empty: "Votre panier est vide.", continue: "Continuer mes achats", subtotal: "Sous-total", shipping: "Livraison", free: "Offerte", total: "Total", checkout: "Passer commande", remove: "Retirer", each: "l'unité" },
    checkout: { title: "Paiement", contact: "Coordonnées de livraison", fullName: "Nom complet", email: "Email", address: "Adresse", city: "Ville", postal: "Code postal", country: "Pays", phone: "Téléphone", payment: "Mode de paiement", card: "Carte bancaire (Stripe)", paypal: "PayPal", paypalSoon: "Bientôt disponible", pay: "Payer", summary: "Récapitulatif", processing: "Traitement…", loginFirst: "Connectez-vous pour finaliser votre commande." },
    payment: { successT: "Paiement confirmé", successD: "Merci pour votre commande ! Un email de confirmation vous sera envoyé.", verifying: "Vérification du paiement…", cancelT: "Paiement annulé", cancelD: "Votre paiement a été annulé. Votre panier est conservé.", orders: "Voir mes commandes", shop: "Retour à la boutique", failed: "Le paiement n'a pas abouti." },
    auth: { loginT: "Connexion", registerT: "Créer un compte", email: "Email", password: "Mot de passe", name: "Nom complet", loginBtn: "Se connecter", registerBtn: "Créer mon compte", noAccount: "Pas encore de compte ?", hasAccount: "Déjà inscrit ?", signup: "Inscrivez-vous", signin: "Connectez-vous" },
    account: { title: "Mon compte", hello: "Bonjour", orders: "Mes commandes", noOrders: "Aucune commande pour le moment.", order: "Commande", status: "Statut", total: "Total", date: "Date", items: "articles", track: "Suivi", invoice: "Facture PDF", invoiceErr: "Facture indisponible.", requestReturn: "Demander un retour", returnPrompt: "Motif du retour ?", returnOk: "Demande de retour envoyée.", returnStatus: "Retour" },
    admin: { title: "Tableau de bord", revenue: "Chiffre d'affaires", orders: "Commandes", paid: "Payées", products: "Produits", customers: "Clients", tabProducts: "Produits", tabOrders: "Commandes", tabCj: "Import CJ", addProduct: "Ajouter un produit", cjSearch: "Rechercher sur CJDropshipping", cjImport: "Importer", margin: "Marge (%)", importAll: "Tout importer", imported: "Importé", importing: "Import…", cjNotConfigured: "Clé API CJDropshipping non configurée. Ajoutez-la pour importer des produits.", newProduct: "Nouveau produit", ptitle: "Titre", pprice: "Prix (€)", pcompare: "Prix barré (€)", pcat: "Catégorie", pimg: "URL image", pdesc: "Description", save: "Enregistrer", delete: "Supprimer", edit: "Modifier", featured: "Vedette", customer: "Client", status: "Statut", tabBlog: "Blog", tabMessages: "Messages", newPost: "Nouvel article", editPost: "Modifier", postTitle: "Titre", excerpt: "Extrait", coverImage: "Image de couverture (URL)", uploadCover: "Téléverser", content: "Contenu", tags: "Tags (séparés par des virgules)", published: "Publié", noPosts: "Aucun article. Créez le premier !", noMessages: "Aucun message.", writeContent: "Rédigez votre article…", savePost: "Enregistrer l'article", tabPromos: "Codes promo", tabSettings: "Réglages", promoCode: "Code", promoType: "Type", promoValue: "Valeur", promoMin: "Sous-total min (€)", promoActive: "Actif", addPromo: "Ajouter un code", noPromos: "Aucun code promo.", percent: "Pourcentage (%)", fixed: "Montant fixe (€)", bannerEnabled: "Bandeau promo activé", bannerText: "Texte du bandeau (FR)", bannerTextEn: "Texte du bandeau (EN)", whatsappEnabled: "Bouton WhatsApp activé", whatsappNumber: "Numéro WhatsApp (format international, ex: 33612345678)", saveSettings: "Enregistrer les réglages", settingsSaved: "Réglages enregistrés", tabAnalytics: "Analytics", tabReturns: "Retours", kpiRevenue: "Chiffre d'affaires", kpiOrders: "Commandes payées", kpiAov: "Panier moyen", kpiConversion: "Taux conversion", kpiVisits: "Visites (30j)", kpiCustomers: "Clients", chartRevenue: "Chiffre d'affaires (30 jours)", chartTop: "Top produits", noReturns: "Aucune demande de retour.", approveRefund: "Approuver & rembourser", reject: "Refuser", returnNote: "Motif du refus (optionnel)", syncStock: "Sync stocks CJ", legalTitle: "Identité légale & facturation", legalHelp: "Obligatoire sur les factures et pour la conformité (facturation électronique / e-reporting).", companyName: "Raison sociale", legalForm: "Forme juridique", vatNumber: "N° TVA intracom.", companyAddress: "Adresse", vatRegime: "Régime TVA", regimeFranchise: "Franchise en base (sans TVA)", regimeAssujetti: "Assujetti à la TVA", vatRate: "Taux de TVA (%)", ereportingExport: "Export e-reporting B2C (CSV)", tabAi: "Studio IA", aiRewriteBtn: "Optimiser avec l'IA", aiImageBtn: "Générer une image IA" },
    footer: { tagline: "La maison connectée, réinventée pour l'Europe.", shop: "Boutique", company: "Entreprise", about: "À propos", contact: "Contact", faq: "Aide & FAQ", legal: "Mentions légales", cgv: "CGV", privacy: "Confidentialité", rights: "Tous droits réservés.", newsletter: "Restez connecté", newsletterD: "Nouveautés et offres, sans spam.", subscribe: "S'inscrire" },
    reviews: { title: "Avis clients", based: "avis", product: "Produit", transport: "Transport / Livraison", write: "Laisser un avis", yourRating: "Note du produit", deliveryRating: "Note de la livraison / transport", comment: "Votre commentaire", placeholder: "Partagez votre expérience produit et livraison…", submit: "Publier mon avis", empty: "Aucun avis pour le moment. Soyez le premier à en laisser un.", verified: "Achat vérifié", mustBuy: "Seuls les acheteurs vérifiés peuvent laisser un avis.", thanks: "Merci pour votre avis !", already: "Vous avez déjà laissé un avis pour ce produit.", loginToReview: "Connectez-vous pour laisser un avis." },
    announce: "Livraison offerte dès 50€ en zone euro · Support bilingue FR / EN",
    newsletterOk: "Merci ! Vous êtes inscrit à la newsletter.",
    contactPage: { title: "Contact", sub: "Une question sur un produit, une commande ou un partenariat ? Écrivez-nous.", name: "Nom", email: "Email", subject: "Sujet", message: "Message", send: "Envoyer le message", sending: "Envoi…", ok: "Message envoyé ! Nous revenons vers vous très vite.", info: "Nous contacter", hours: "Support bilingue FR / EN · 7j/7" },
    blog: { title: "Journal", sub: "Guides, tendances et conseils sur la maison connectée et le télétravail.", read: "Lire l'article", empty: "Aucun article pour le moment.", back: "Tous les articles", by: "Par", min: "min de lecture" },
    home: { journalTitle: "Le Journal", journalSub: "Guides & tendances pour votre maison connectée.", journalAll: "Tous les articles", socialTitle: "Ils nous font confiance", socialSub: "Ce que disent nos clients vérifiés." },
    wishlist: { title: "Mes favoris", empty: "Votre liste de favoris est vide.", add: "Ajouter aux favoris", remove: "Retirer des favoris", added: "Ajouté aux favoris ♥", removed: "Retiré des favoris", loginFirst: "Connectez-vous pour enregistrer vos favoris.", browse: "Explorer la boutique" },
    promo: { label: "Code promo", apply: "Appliquer", placeholder: "Votre code", applied: "Code appliqué", invalid: "Code invalide ou non applicable.", remove: "Retirer", discount: "Réduction" },
    popup: { title: "-10% sur votre 1ère commande", sub: "Inscrivez-vous à la newsletter et recevez votre code de bienvenue.", placeholder: "votre@email.com", cta: "Recevoir mon code -10%", code: "Votre code de bienvenue", later: "Non merci", thanksT: "Bienvenue chez Invovix !", success: "Voici votre code, à utiliser au panier :", shopNow: "J'en profite" },
    whatsapp: { label: "Une question ? Écrivez-nous" },
    search: { placeholder: "Rechercher un produit…", empty: "Aucun résultat.", title: "Recherche" },
    related: { title: "Vous aimerez aussi" },
    faq: { title: "Aide & FAQ", sub: "Livraison, retours, paiement : tout ce qu'il faut savoir avant de commander.", shippingT: "Livraison", shippingD: "Offerte dès 50€, partout en zone euro. Suivi fourni.", returnsT: "Retours 30 jours", returnsD: "Satisfait ou remboursé sous 30 jours.", contactT: "Un souci ?", contactD: "Notre support bilingue vous répond 7j/7.", items: [ {q:"Quels sont les délais de livraison ?", a:"Vos commandes sont préparées sous 24 à 48h. La livraison en zone euro prend ensuite entre 5 et 12 jours ouvrés selon le produit. Un numéro de suivi vous est envoyé par email."}, {q:"La livraison est-elle gratuite ?", a:"Oui, la livraison est offerte pour toute commande à partir de 50€. En dessous, une participation de 4,90€ s'applique."}, {q:"Puis-je retourner un article ?", a:"Vous disposez de 30 jours après réception pour changer d'avis. Contactez-nous et nous organisons le retour et le remboursement."}, {q:"Quels moyens de paiement acceptez-vous ?", a:"Nous acceptons les cartes bancaires via Stripe ainsi que PayPal. Toutes les transactions sont chiffrées (SSL)."}, {q:"Mes données sont-elles protégées ?", a:"Absolument. Nous ne stockons jamais vos informations de paiement et vos formulaires sont protégés contre le spam (reCAPTCHA)."}, {q:"Comment vous contacter ?", a:"Via notre page Contact ou par WhatsApp. Notre support bilingue FR/EN vous répond rapidement."} ] },
    cookie: { text: "Nous utilisons des cookies pour mesurer l'audience et améliorer votre expérience.", accept: "Accepter", refuse: "Refuser", link: "En savoir plus" },
    common: { loading: "Chargement…" },
  },
  en: {
    nav: { shop: "Shop", smartHome: "Smart Home", workspace: "Remote Work", security: "Security", story: "Manifesto", blog: "Blog", contact: "Contact", account: "Account", admin: "Admin", login: "Login", logout: "Logout", cart: "Cart" },
    hero: { overline: "Premium smart home · Europe delivery", l1: "The home", l2: "that thinks", l3: "for you.", sub: "Invovix designs a connected ecosystem for the smart home and remote work. Considered objects, delivered across the eurozone.", cta: "Explore the shop", cta2: "Our manifesto" },
    marquee: ["Smart Home", "Remote Work", "Intelligent Security", "Europe Delivery", "EN / FR Support"],
    featured: { overline: "Selection", title: "Connected essentials", sub: "A curation of technical objects to transform your everyday.", all: "Browse the full shop" },
    categories: { overline: "Worlds", title: "Explore by use", smartHome: "Smart Home", smartHomeD: "Lighting, thermostats, hubs.", workspace: "Remote Work", workspaceD: "Augmented, wireless desks.", security: "Security", securityD: "Smart cameras & sensors." },
    manifesto: { overline: "The Invovix manifesto", c1t: "Technology disappears", c1d: "The best connected object is the one you forget. It acts, anticipates and fades away. We design for radical simplicity.", c2t: "Built to last", c2d: "Every product is selected for its reliability and native integration into your existing ecosystem.", c3t: "Delivered in Europe", c3d: "Logistics built for the eurozone. Prices in euros, bilingual support, tracked delivery." },
    trust: { free: "Free shipping from €50", freeD: "Everywhere in the eurozone", secure: "Secure payment", secureD: "Stripe & PayPal, SSL encrypted", support: "Bilingual support", supportD: "EN / FR assistance 7/7", returns: "30-day returns", returnsD: "Satisfied or refunded" },
    cta: { title: "Ready to connect your space?", sub: "Join the homes that chose discreet intelligence.", btn: "Get started" },
    shop: { title: "The shop", sub: "All our connected objects, curated for Europe.", filterAll: "All", empty: "No products found.", search: "Search…" },
    product: { add: "Add to cart", added: "Added to cart", buy: "Buy now", desc: "Description", back: "Back", inStock: "In stock", outOfStock: "Sold out", lowStock: "Only {n} left", variant: "Option", qty: "Quantity", save: "Save" },
    cart: { title: "Your cart", empty: "Your cart is empty.", continue: "Continue shopping", subtotal: "Subtotal", shipping: "Shipping", free: "Free", total: "Total", checkout: "Checkout", remove: "Remove", each: "each" },
    checkout: { title: "Checkout", contact: "Shipping details", fullName: "Full name", email: "Email", address: "Address", city: "City", postal: "Postal code", country: "Country", phone: "Phone", payment: "Payment method", card: "Credit card (Stripe)", paypal: "PayPal", paypalSoon: "Coming soon", pay: "Pay", summary: "Summary", processing: "Processing…", loginFirst: "Log in to complete your order." },
    payment: { successT: "Payment confirmed", successD: "Thank you for your order! A confirmation email is on its way.", verifying: "Verifying payment…", cancelT: "Payment cancelled", cancelD: "Your payment was cancelled. Your cart is saved.", orders: "View my orders", shop: "Back to shop", failed: "Payment did not complete." },
    auth: { loginT: "Login", registerT: "Create account", email: "Email", password: "Password", name: "Full name", loginBtn: "Sign in", registerBtn: "Create account", noAccount: "No account yet?", hasAccount: "Already registered?", signup: "Sign up", signin: "Sign in" },
    account: { title: "My account", hello: "Hello", orders: "My orders", noOrders: "No orders yet.", order: "Order", status: "Status", total: "Total", date: "Date", items: "items", track: "Track", invoice: "PDF invoice", invoiceErr: "Invoice unavailable.", requestReturn: "Request a return", returnPrompt: "Reason for return?", returnOk: "Return request sent.", returnStatus: "Return" },
    admin: { title: "Dashboard", revenue: "Revenue", orders: "Orders", paid: "Paid", products: "Products", customers: "Customers", tabProducts: "Products", tabOrders: "Orders", tabCj: "CJ Import", addProduct: "Add product", cjSearch: "Search CJDropshipping", cjImport: "Import", margin: "Margin (%)", importAll: "Import all", imported: "Imported", importing: "Importing…", cjNotConfigured: "CJDropshipping API key not configured. Add it to import products.", newProduct: "New product", ptitle: "Title", pprice: "Price (€)", pcompare: "Compare-at price (€)", pcat: "Category", pimg: "Image URL", pdesc: "Description", save: "Save", delete: "Delete", edit: "Edit", featured: "Featured", customer: "Customer", status: "Status", tabBlog: "Blog", tabMessages: "Messages", newPost: "New post", editPost: "Edit", postTitle: "Title", excerpt: "Excerpt", coverImage: "Cover image (URL)", uploadCover: "Upload", content: "Content", tags: "Tags (comma separated)", published: "Published", noPosts: "No posts yet. Create the first one!", noMessages: "No messages.", writeContent: "Write your article…", savePost: "Save post", tabPromos: "Promo codes", tabSettings: "Settings", promoCode: "Code", promoType: "Type", promoValue: "Value", promoMin: "Min subtotal (€)", promoActive: "Active", addPromo: "Add code", noPromos: "No promo codes.", percent: "Percentage (%)", fixed: "Fixed amount (€)", bannerEnabled: "Promo banner enabled", bannerText: "Banner text (FR)", bannerTextEn: "Banner text (EN)", whatsappEnabled: "WhatsApp button enabled", whatsappNumber: "WhatsApp number (international format, e.g. 33612345678)", saveSettings: "Save settings", settingsSaved: "Settings saved", tabAnalytics: "Analytics", tabReturns: "Returns", kpiRevenue: "Revenue", kpiOrders: "Paid orders", kpiAov: "Avg. order value", kpiConversion: "Conversion rate", kpiVisits: "Visits (30d)", kpiCustomers: "Customers", chartRevenue: "Revenue (30 days)", chartTop: "Top products", noReturns: "No return requests.", approveRefund: "Approve & refund", reject: "Reject", returnNote: "Rejection reason (optional)", syncStock: "Sync CJ stock", legalTitle: "Legal identity & invoicing", legalHelp: "Required on invoices and for compliance (e-invoicing / e-reporting).", companyName: "Company name", legalForm: "Legal form", vatNumber: "VAT number", companyAddress: "Address", vatRegime: "VAT regime", regimeFranchise: "VAT-exempt (franchise)", regimeAssujetti: "VAT-registered", vatRate: "VAT rate (%)", ereportingExport: "Export B2C e-reporting (CSV)", tabAi: "AI Studio", aiRewriteBtn: "Optimize with AI", aiImageBtn: "Generate AI image" },
    footer: { tagline: "The connected home, reinvented for Europe.", shop: "Shop", company: "Company", about: "About", contact: "Contact", faq: "Help & FAQ", legal: "Legal notice", cgv: "Terms", privacy: "Privacy", rights: "All rights reserved.", newsletter: "Stay connected", newsletterD: "News and offers, no spam.", subscribe: "Subscribe" },
    reviews: { title: "Customer reviews", based: "reviews", product: "Product", transport: "Shipping / Delivery", write: "Write a review", yourRating: "Product rating", deliveryRating: "Delivery / shipping rating", comment: "Your comment", placeholder: "Share your product and delivery experience…", submit: "Publish my review", empty: "No reviews yet. Be the first to leave one.", verified: "Verified purchase", mustBuy: "Only verified buyers can leave a review.", thanks: "Thanks for your review!", already: "You already reviewed this product.", loginToReview: "Log in to leave a review." },
    announce: "Free shipping from €50 in the eurozone · EN / FR bilingual support",
    newsletterOk: "Thanks! You're subscribed to the newsletter.",
    contactPage: { title: "Contact", sub: "A question about a product, an order or a partnership? Write to us.", name: "Name", email: "Email", subject: "Subject", message: "Message", send: "Send message", sending: "Sending…", ok: "Message sent! We'll get back to you shortly.", info: "Get in touch", hours: "Bilingual EN / FR support · 7/7" },
    blog: { title: "Journal", sub: "Guides, trends and tips on the connected home and remote work.", read: "Read article", empty: "No articles yet.", back: "All articles", by: "By", min: "min read" },
    home: { journalTitle: "The Journal", journalSub: "Guides & trends for your connected home.", journalAll: "All articles", socialTitle: "Loved by our customers", socialSub: "What our verified buyers say." },
    wishlist: { title: "My wishlist", empty: "Your wishlist is empty.", add: "Add to wishlist", remove: "Remove from wishlist", added: "Added to wishlist ♥", removed: "Removed from wishlist", loginFirst: "Log in to save your favourites.", browse: "Browse the shop" },
    promo: { label: "Promo code", apply: "Apply", placeholder: "Your code", applied: "Code applied", invalid: "Invalid or non-applicable code.", remove: "Remove", discount: "Discount" },
    popup: { title: "-10% on your 1st order", sub: "Join the newsletter and get your welcome code.", placeholder: "you@email.com", cta: "Get my -10% code", code: "Your welcome code", later: "No thanks", thanksT: "Welcome to Invovix!", success: "Here is your code, use it at checkout:", shopNow: "Shop now" },
    whatsapp: { label: "A question? Message us" },
    search: { placeholder: "Search a product…", empty: "No results.", title: "Search" },
    related: { title: "You may also like" },
    faq: { title: "Help & FAQ", sub: "Shipping, returns, payment: everything you need before ordering.", shippingT: "Shipping", shippingD: "Free from €50, everywhere in the eurozone. Tracking included.", returnsT: "30-day returns", returnsD: "Satisfied or refunded within 30 days.", contactT: "An issue?", contactD: "Our bilingual support replies 7/7.", items: [ {q:"What are the delivery times?", a:"Orders are prepared within 24–48h. Eurozone delivery then takes 5 to 12 business days depending on the product. A tracking number is emailed to you."}, {q:"Is shipping free?", a:"Yes, shipping is free on any order from €50. Below that, a €4.90 fee applies."}, {q:"Can I return an item?", a:"You have 30 days after delivery to change your mind. Contact us and we'll arrange the return and refund."}, {q:"Which payment methods do you accept?", a:"We accept credit cards via Stripe and PayPal. All transactions are SSL-encrypted."}, {q:"Is my data protected?", a:"Absolutely. We never store your payment details and our forms are spam-protected (reCAPTCHA)."}, {q:"How can I contact you?", a:"Via our Contact page or WhatsApp. Our bilingual EN/FR support replies quickly."} ] },
    cookie: { text: "We use cookies to measure audience and improve your experience.", accept: "Accept", refuse: "Decline", link: "Learn more" },
    common: { loading: "Loading…" },
  },
};

const I18nContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(localStorage.getItem("invovix_lang") || "fr");
  const toggle = useCallback(() => {
    setLang((l) => {
      const next = l === "fr" ? "en" : "fr";
      localStorage.setItem("invovix_lang", next);
      return next;
    });
  }, []);
  const t = translations[lang];
  return <I18nContext.Provider value={{ lang, t, toggle, setLang }}>{children}</I18nContext.Provider>;
}

export function useI18n() {
  return useContext(I18nContext);
}
